version: '3.6'

services:
  #Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  #Postgres
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: orinayo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
  #Backend API
  facerecognition-api:
    container_name: backend
    build: ./
    working_dir: /usr/src/facerecognition-api
    environment:
      POSTGRES_URI: postgres://orinayo:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
      JWT_SECRET: secret
    links:
      - postgres
      - redis
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/facerecognition-api